Repository prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang, pull requests merged in 2023-09, with the labels that each got.

#8 Prettier Plugin 설치
  .prettierrc
  package-lock.json
  package.json
Labels: 기능

#12 pr 템플릿 이름 변경
  .github/pull_request_template.md
Labels: 긴급

#13 eslint 관련 작업
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: 기능

#21 eslint 관련 설정
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: 리팩터링

#22 storybook 설치 및 기본 파일 삭제
  .eslintrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  tailwind.config.js
Labels: 기능, 문서

#23 라우팅 관련 작업
  package-lock.json
  package.json
  src/App.tsx
  src/constants/index.ts
  src/constants/path.ts
  src/pages/HomePage.tsx
  src/pages/index.ts
Labels: 기능

#24 api 기본 설정 작업
  .eslintrc.cjs
  .gitignore
  src/App.tsx
  src/api/index.ts
  src/api/snsApiClient.ts
Labels: 기능

#27 로그인 기능 추가
  src/api/apiClient.ts
  src/api/index.ts
  src/api/snsApiClient.ts
  src/pages/HomePage.tsx
  src/services/channelService.ts
  src/services/index.ts
  src/services/userService.ts
Labels: 기능

#31 예제 스토리북 추가
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/mocks/components/MyComponent.stories.tsx
  src/mocks/components/MyComponent.tsx
Labels: 기능

#32 회원가입 api 관련 작업
  .env.dev
  .eslintrc.cjs
  src/hooks/useForm.ts
  src/pages/HomePage.tsx
  src/services/userService.ts
Labels: 기능

#35 버튼 컴포넌트 생성 및 팔레트 세팅
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  tailwind.config.js
Labels: 기능, 질문

#46 Button 컴포넌트 리팩토링
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Buttons/Button.stories.tsx
  src/components/Buttons/Button.tsx
  src/components/Buttons/index.ts
  src/pages/HomePage.tsx
Labels: 리팩터링

#48 Avatar 컴포넌트 초기 생성 및 storybook 추가
  src/components/Avatar/Avatar.stories.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/index.ts
Labels: 기능

#42 Input 컴포넌트 생성
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
Labels: 기능

#55 dayjs 라이브러리 추가
  package-lock.json
  package.json
Labels: 기능

#56 Import 관련 설정
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/constants/index.ts
  src/hooks/index.ts
  src/main.tsx
  src/pages/HomePage.tsx
  src/routes/router.tsx
  src/services/channelService.ts
  src/services/userService.ts
  tsconfig.json
  vite.config.ts
Labels: 문서

#57 Card 컴포넌트 추가(Card, CardTitle)
  src/components/Cards/Card.stories.tsx
  src/components/Cards/Card.tsx
  src/components/Cards/CardTitle.tsx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.tsx
  src/components/Image/index.ts
Labels: 기능

#66 게시물 생성 api 작업
  src/App.tsx
  src/pages/HomePage.tsx
  src/services/channelService.ts
  src/services/index.ts
  src/services/postService.ts
Labels: 기능

#69 특정 포스트 상세 api 작업
  src/services/postService.ts
Labels: 기능

#75 Eslint 규칙 추가 작업
  .eslintrc.cjs
  src/components/Cards/Card.stories.tsx
  src/components/Image/Image.tsx
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/hooks/userStorage.ts
  src/pages/HomePage.tsx
Labels: 기능

#78 게시물 댓글 관련 작업
  src/pages/HomePage.tsx
  src/services/commentService.ts
  src/services/index.ts
Labels: 기능

#79 스타일 설정 작업
  src/components/Avatar/Avatar.tsx
  src/components/Badge/Badge.tsx
  src/components/Buttons/Button.tsx
  src/styles/fonts/OAGothic-Medium.ttf
  src/styles/index.css
  tailwind.config.js
Labels: 기능, 문서

#81 라우팅 관련 작업
  src/pages/ChatDetailPage.tsx
  src/pages/ChatPage.tsx
  src/pages/FollowPage.tsx
  src/pages/PostEditPage.tsx
  src/pages/PostPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SignupPage.tsx
  src/pages/index.ts
  src/routes/Layout.tsx
  src/routes/constants.ts
  src/routes/router.tsx
Labels: 기능, 스타일

#61 게시물 왼쪽 상단에 하트 버튼 생성
  src/components/Buttons/IconButton.tsx
  src/components/Buttons/IcontButton.stories.tsx
  src/components/Buttons/index.ts
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/IconSet.ts
  src/components/Icon/index.ts
  src/components/index.ts
  src/pages/HomePage.tsx
Labels: 기능

#82 프로필 헤더 제작 및 useUser 방식 변경
  src/api/snsApiClient.ts
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/hooks/userStorage.ts
  src/pages/ProfilePage/ProfileHeader.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/index.ts
  src/services/postService.ts
Labels: 기능, 리팩터링

#91 회원가입 페이지 디자인 작업
  src/pages/SignupPage.tsx
Labels: 긴급, 스타일

#92 메인 페이지 디자인
  src/assets/seated_man.svg
  src/pages/HomePage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/SeatedMan.tsx
  src/pages/HomePage/index.ts
  src/pages/index.ts
Labels: 긴급, 스타일

#95 404 페이지 디자인
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/NotFoundPage/Warning.tsx
  src/pages/NotFoundPage/index.ts
  src/pages/index.ts
  src/routes/router.tsx
Labels: 긴급, 스타일

#97 게시물 작성 페이지 디자인 작업
  src/pages/PostEditPage.tsx
  src/routes/Layout.tsx
Labels: 긴급, 스타일

#96 layout, homepage 컴포넌트 디자인 수정
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/SeatedMan.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/SignupPage.tsx
  src/routes/Layout.tsx
Labels: 스타일

#71 List 컴포넌트 작업
  src/components/List/List.stories.tsx
  src/components/List/List.tsx
  src/components/List/index.ts
  src/components/index.ts
Labels: 기능

#106 api types 추가
  src/types/model.ts
Labels: 기능

#115 전체 너비 768px로 변경
  index.html
  src/pages/HomePage/HomePage.tsx
  src/routes/Layout.tsx
  src/routes/LayoutWithFooter.tsx
  tailwind.config.js
Labels: 긴급, 스타일

#114 무한 스크롤 리팩토링
  src/hooks/useInfiniteScroll.ts
Labels: 리팩터링

#77 포스트 목록 받아오기 api 생성
  src/services/postService.ts
Labels: 기능

#124 스크롤바 제거 작업
  src/pages/HomePage/HomePage.tsx
  tailwind.config.js
Labels: 리팩터링

#118 회원가입 페이지 수정
  src/pages/SignupPage.tsx
Labels: 리팩터링

#120 스토리북 사용 컴포넌트 수정
  package-lock.json
  package.json
  src/components/common/Avatar/Avatar.stories.tsx
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Badge/Badge.stories.tsx
  src/components/common/Badge/Badge.tsx
  src/components/common/Buttons/Button.stories.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Cards/Card.stories.tsx
  src/components/common/Cards/Card.tsx
  src/components/common/Cards/CardTitle.tsx
  src/components/common/Cards/index.ts
  src/components/common/Image/Image.stories.tsx
  src/components/common/Image/Image.tsx
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.tsx
  src/components/domain/List/List.stories.tsx
  src/components/domain/List/List.tsx
  src/components/domain/PostItem/PostItem.stories.tsx
  src/components/domain/PostItem/PostItem.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/PostEditPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/SignupPage.tsx
  src/services/postService.ts
Labels: 리팩터링, 스타일

#121 Header 컴포넌트 생성
  src/assets/left-arrow.svg
  src/components/domain/Header/Header.stories.tsx
  src/components/domain/Header/Header.tsx
  src/components/domain/Header/index.ts
  src/components/domain/index.ts
  src/pages/HomePage/HomePage.tsx
Labels: 기능

#128 스토리북 toast 컴포넌트 관련 작업
  .storybook/preview.tsx
  src/App.tsx
  src/components/common/Toast/README.md
  src/components/common/Toast/Toast.stories.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/components/common/Toast/ToastProvider.tsx
  src/components/common/Toast/index.ts
  src/components/common/Toast/util.ts
  src/components/common/index.ts
  src/pages/HomePage/HomePage.tsx
Labels: 기능, 스타일

#136 Footer 컴포넌트 생성
  src/assets/chat.svg
  src/assets/home.svg
  src/assets/pencil.svg
  src/assets/person.svg
  src/components/domain/Footer/Footer.tsx
  src/components/domain/Footer/index.ts
  src/components/domain/index.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/PostEditPage.tsx
  src/routes/Layout.tsx
  src/routes/LayoutWithFooter.tsx
  tailwind.config.js
Labels: 기능, 스타일

#137 Commentitem 컴포넌트 작업
  src/assets/index.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/domain/CommentItem/CommentItem.stories.tsx
  src/components/domain/CommentItem/CommentItem.tsx
  src/components/domain/CommentItem/index.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
Labels: 기능

#141 가로 스크롤 컴포넌트 구현
  src/components/common/Avatar/Avatar.tsx
  src/components/common/HorizontalScroll/HorizontalScroll.stories.tsx
  src/components/common/HorizontalScroll/HorizontalScroll.tsx
  src/components/common/HorizontalScroll/index.ts
  src/components/common/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/ChannelItem.tsx
  src/pages/HomePage/components/ChannelList.tsx
  src/pages/HomePage/components/index.ts
Labels: 기능

#144 Notification 목록 받아오기 api 관련 작업
  src/services/notificationService.ts
Labels: 기능, 긴급

#132 Useuser 수정
  src/api/snsApiClient.ts
  src/hooks/useUser.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/routes/Layout.tsx
  src/types/index.ts
  src/utils/index.ts
  src/utils/userStorage.ts
Labels: 기능, 리팩터링, 긴급

#146 Signuppage 관련 수정
  src/hooks/usePassword.ts
  src/pages/SignupPage.tsx
  src/utils/validations.ts
Labels: 기능

#127 포스트 목록 받아오기 api 관련 작업
  src/components/domain/List/List.tsx
  src/pages/ChannelListPage.tsx
  src/pages/PostListPage.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/postService.ts
  src/types/model.ts
Labels: 기능, 리팩터링, 긴급

#150 chore: 함수 반환 타입 지정
  src/services/notificationService.ts
Labels: 리팩터링

#153 로그인 모달창 스타일 적용
  src/components/common/Modal/LoginForm.tsx
  src/components/common/Modal/Modal.tsx
Labels: 스타일

#160 스토리북 네이밍 작업
  src/components/common/HorizontalScroll/HorizontalScroll.stories.tsx
  src/components/domain/Header/Header.stories.tsx
Labels: 리팩터링

#157 게시글 목록 페이지 관련 작업
  src/components/domain/PostCard/PostCard.stories.tsx
  src/components/domain/PostCard/PostCard.tsx
  src/components/domain/PostCard/index.ts
  src/components/domain/PostItem/PostItem.stories.tsx
  src/components/domain/PostItem/PostItem.tsx
  src/components/domain/PostItem/index.ts
  src/components/domain/PostList/PostList.tsx
  src/components/domain/PostList/index.ts
  src/components/domain/index.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/ChannelListPage.tsx
  src/pages/channelPage/ChannelPage.tsx
  src/pages/channelPage/constants.ts
  src/pages/channelPage/index.ts
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/channelService.ts
  src/services/postService.ts
Labels: 기능

#161 Header 컴포넌트 수정
  .storybook/preview.tsx
  src/components/domain/Footer/Footer.tsx
  src/components/domain/Header/Header.stories.tsx
  src/components/domain/Header/Header.tsx
  src/hooks/index.ts
  src/hooks/useUserNotifications.ts
  src/routes/Layout.tsx
  src/services/notificationService.ts
Labels: 기능, 리팩터링

#162 글 작성 페이지
  src/components/domain/Footer/Footer.tsx
  src/hooks/index.ts
  src/hooks/useForm.ts
  src/hooks/useHandlePost.ts
  src/pages/PostCreatePage/ChannelList.tsx
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/PostCreatePage/index.ts
  src/pages/PostListPage.tsx
  src/pages/channelPage/ChannelPage.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/channelService.ts
  src/services/postService.ts
  src/utils/validations.ts
Labels: 기능

#155 메인 페이지, 가로 스크롤 마우스 이벤트 비동기 처리
  src/assets/eye-on.svg
  src/assets/icons/bell.svg
  src/assets/icons/chat.svg
  src/assets/icons/close.svg
  src/assets/icons/comment.svg
  src/assets/icons/dots.svg
  src/assets/icons/eye-off.svg
  src/assets/icons/eye-on.svg
  src/assets/icons/heart.svg
  src/assets/icons/home.svg
  src/assets/icons/image.svg
  src/assets/icons/index.ts
  src/assets/icons/left-arrow.svg
  src/assets/icons/pencil.svg
  src/assets/icons/person.svg
  src/assets/icons/right-arrow.svg
  src/assets/icons/search.svg
  src/assets/icons/seated-man.svg
  src/assets/images/seated-man.png
  src/assets/index.ts
  src/components/common/HorizontalScroll/HorizontalScroll.tsx
  src/components/domain/CommentItem/index.ts
  src/components/domain/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/SeatedMan.tsx
  src/pages/HomePage/components/ChannelInfo.tsx
  src/pages/HomePage/components/ChannelItem.tsx
  src/pages/HomePage/components/ChannelList.tsx
  src/pages/HomePage/components/index.ts
  src/pages/HomePage/constants.ts
  src/pages/HomePage/index.ts
  src/utils/getRandomItem.ts
  src/utils/index.ts
Labels: 기능, 리팩터링, 긴급

#165 프로필 페이지 기능 추가
  src/components/common/Modal/LoginForm.tsx
  src/components/common/Modal/Modal.tsx
  src/components/domain/Footer/Footer.tsx
  src/components/domain/PostItem/PostItem.tsx
  src/hooks/useUser.ts
  src/pages/FollowPage/FollowPage.tsx
  src/pages/FollowPage/UserList.tsx
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/index.ts
  src/pages/ProfilePage/ProfileHeader.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/userService.ts
  src/types/model.ts
Labels: 기능

#170 vercel 라우팅 관련 설정
  vercel.json
Labels: 긴급

#168 PostList 컴포넌트 스타일 변경
  src/assets/images/Logo.svg
  src/components/domain/PostCard/PostCard.tsx
  src/components/domain/PostList/PostList.tsx
  src/pages/HomePage/HomePage.tsx
  src/routes/Layout.tsx
  src/utils/getRandomItem.ts
Labels: 리팩터링, 스타일

#172 Header 컴포넌트 수정 다시
  src/components/domain/Header/Header.tsx
  src/pages/FollowPage/FollowPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/channelPage/ChannelPage.tsx
Labels: 리팩터링

#177 프로필 설정 페이지 추가 및 기능 구현
  src/components/common/Modal/CheckForm.tsx
  src/components/common/Modal/index.ts
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/components/ProfileEditInput.tsx
  src/pages/ProfileEditPage/components/ProfileEditLabel.tsx
  src/pages/ProfileEditPage/components/ProfileEditWrapper.tsx
  src/pages/ProfileEditPage/components/ProfileFullName.tsx
  src/pages/ProfileEditPage/components/ProfilePassword.tsx
  src/pages/ProfileEditPage/components/ProfileSignOut.tsx
  src/pages/ProfileEditPage/components/index.ts
  src/pages/ProfilePage/ProfileHeader.tsx
Labels: 기능

#174 SignupPage, Header, PostCreatePage 수정
  src/components/domain/Header/Header.tsx
  src/hooks/useAuth.ts
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/SignUpPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/index.ts
  src/pages/index.ts
  src/routes/constants.ts
Labels: 리팩터링

#179 배포 관련 사항 및 footer 수정
  src/components/domain/Header/Header.tsx
  src/pages/FollowPage/FollowPage.tsx
  src/pages/FollowPage/UserList.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/routes/Layout.tsx
Labels: 리팩터링, 스타일

#173 채팅 관련 작업
  src/components/domain/Footer/Footer.tsx
  src/pages/ChatDetailPage.tsx
  src/pages/ChatPage.tsx
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ChatPage/index.ts
  src/pages/ConversationPage/ConversationPage.tsx
  src/pages/ConversationPage/index.ts
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/messageService.ts
Labels: 기능

#186 채널별 기본 이미지 적용
  src/assets/images/clean.png
  src/assets/images/cook.png
  src/assets/images/decor.png
  src/assets/images/general.png
  src/assets/images/help.png
  src/components/domain/PostCard/PostCard.tsx
  src/components/domain/PostCard/constants.ts
  src/components/domain/PostList/PostList.tsx
Labels: 리팩터링, 스타일

#183 상세 채널 페이지 디자인 추가
  src/components/domain/PostList/PostList.tsx
  src/pages/channelPage/ChannelPage.tsx
  src/routes/router.tsx
Labels: 스타일

#198 프로필 페이지 미구현 기능 추가 중간 merge
  src/pages/LikeListPage/LikeListPage.tsx
  src/pages/LikeListPage/index.ts
  src/pages/ProfilePage/ProfileHeader.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/postService.ts
Labels: 기능

#200 프록시를 통한 엔드포인트 숨기기
  src/api/snsApiClient.ts
  vite.config.ts
Labels: 기능

#192 Menu 컴포넌트 구현
  src/components/common/Menu/Menu.tsx
  src/components/common/Menu/MenuItem.tsx
  src/components/common/Menu/index.ts
  src/components/common/index.ts
  src/hooks/useModal.ts
  src/pages/HomePage/HomePage.tsx
Labels: 기능, 리팩터링

#195 React query 관련 작업
  src/App.tsx
  src/components/domain/Footer/Footer.tsx
  src/hooks/useUser.ts
  src/hooks/useUserNotifications.ts
  src/pages/ConversationPage/ConversationPage.tsx
  src/pages/FollowPage/UserList.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ProfileEditPage/components/ProfileFullName.tsx
  src/pages/ProfilePage/ProfileHeader.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/routes/Layout.tsx
  src/services/channelService.ts
  src/services/userService.ts
  src/utils/assert.ts
Labels: 기능

#202 상세 게시글 페이지 리팩토링
  src/components/domain/CommentItem/CommentItem.tsx
  src/pages/PostPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/index.ts
  src/pages/index.ts
  src/services/commentService.ts
  src/services/postService.ts
Labels: 기능, 리팩터링

#203 알림 기능 작업
  src/pages/HomePage/HomePage.tsx
  src/pages/NotificationsPage/NotificationsPage.tsx
  src/pages/NotificationsPage/components/NotificationItem.tsx
  src/pages/NotificationsPage/components/NotificationList.tsx
  src/pages/NotificationsPage/components/index.ts
  src/pages/NotificationsPage/constants.ts
  src/pages/NotificationsPage/index.ts
  src/pages/PostPage/PostPage.tsx
  src/pages/channelPage/ChannelPage.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/notificationService.ts
Labels: 기능

#210 메시지 관련 디자인 작업
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ConversationPage/ConversationPage.tsx
  src/routes/router.tsx
  src/services/userService.ts
Labels: 스타일

#206 무한 스크롤 기능 수정
  src/components/domain/PostList/PostList.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/channelPage/ChannelPage.tsx
Labels: 기능

#219 favicon 추가
  index.html
  src/assets/icons/honkok.png
Labels: 스타일

#211 프로필 페이지 거의 완성
  src/assets/icons/index.ts
  src/assets/icons/setting.svg
  src/components/common/Avatar/Avatar.tsx
  src/components/domain/PostCard/PostCard.tsx
  src/hooks/useUser.ts
  src/pages/FollowPage/FollowPage.tsx
  src/pages/FollowPage/UserList.tsx
  src/pages/LikeListPage/LikeListPage.tsx
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/components/ProfileFullName.tsx
  src/pages/ProfileEditPage/components/ProfilePassword.tsx
  src/pages/ProfileEditPage/components/ProfileSetting.tsx
  src/pages/ProfileEditPage/components/ProfileSignOut.tsx
  src/pages/ProfileEditPage/components/index.ts
  src/pages/ProfilePage/ProfileHeader.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/services/postService.ts
  src/services/userService.ts
Labels: 기능, 리팩터링

#212 Useuser 서버 재요청 해결
  src/hooks/useUser.ts
Labels: 리팩터링

#218 Postlist 버그 수정
  src/hooks/useInfiniteScroll.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/channelPage/ChannelPage.tsx
  src/services/postService.ts
Labels: 리팩터링

#217 헤더 컴포넌트 수정
  src/components/domain/Header/Header.tsx
  src/hooks/useUser.ts
  src/services/notificationService.ts
Labels: 리팩터링

#222 feat: Header 컴포넌트 로그인 상태에 따른 아이콘 표시 및 navigate 수정
  src/components/domain/Header/Header.tsx
Labels: 리팩터링

#228 로그인 실패 시 토스트 띄워주기
  src/components/common/Modal/LoginForm.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/hooks/useAuth.ts
Labels: 기능

#226 간단한 에러 관련 작업
  src/components/common/Badge/Badge.tsx
  src/components/domain/CommentItem/CommentItem.tsx
  src/components/domain/PostList/PostList.tsx
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/ChannelPage/constants.ts
  src/pages/ChannelPage/index.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/PostEditPage/PostEditPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/services/postService.ts
Labels: 기능, 리팩터링, 긴급, 버그

#232 postcard 컴포넌트 이미지 비율 조정
  src/components/domain/PostCard/PostCard.tsx
Labels: 스타일

#233 게시글 페이지 디자인 수정 작업
  src/assets/icons/dots.svg
  src/components/common/Menu/Menu.tsx
  src/components/common/Menu/MenuItem.tsx
  src/components/common/Modal/Modal.tsx
  src/components/domain/CommentItem/CommentItem.tsx
  src/components/domain/PostList/PostList.tsx
  src/pages/PostEditPage/PostEditPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/components/PostComment.tsx
  src/pages/PostPage/components/PostContent.tsx
  src/pages/PostPage/components/PostInfo.tsx
  src/pages/PostPage/components/PostLike.tsx
  src/pages/PostPage/components/index.ts
  src/pages/channelPage/ChannelPage.tsx
  src/pages/channelPage/constants.ts
  src/pages/channelPage/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/types/model.ts
Labels: 기능, 리팩터링, 스타일

#237 게시글 페이지 리팩토링
  src/pages/PostEditPage/PostEditPage.tsx
  src/pages/PostPage/PostPage.tsx
Labels: 기능, 리팩터링

#240 ProfilePage 리팩토링
  src/components/common/Avatar/Avatar.tsx
  src/pages/FollowPage/FollowPage.tsx
  src/pages/FollowPage/UserList.tsx
  src/pages/ProfileEditPage/components/ProfileEditLabel.tsx
  src/pages/ProfilePage/ProfileHeader.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/services/userService.ts
Labels: 리팩터링, 스타일

#245 게시글 작성 페이지 스타일 수정
  src/components/common/Input/Input.tsx
  src/pages/PostCreatePage/PostCreatePage.tsx
Labels: 기능

#244 알림 페이지 스타일 및 리팩토링 작업
  src/assets/icons/yellow-bell.png
  src/components/domain/Header/Header.tsx
  src/pages/FollowPage/FollowPage.tsx
  src/pages/FollowPage/UserList.tsx
  src/pages/NotificationsPage/NotificationsPage.tsx
  src/pages/NotificationsPage/components/NotificationItem.tsx
  src/pages/NotificationsPage/components/NotificationList.tsx
  src/pages/NotificationsPage/constants.ts
  src/pages/ProfilePage/ProfileHeader.tsx
  src/types/model.ts
Labels: 기능, 리팩터링, 스타일

#246 유효성 검사 관련 작업
  src/components/common/Modal/CheckForm.tsx
  src/components/common/Modal/LoginForm.tsx
  src/components/common/Modal/Modal.tsx
  src/hooks/usePassword.ts
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/PostCreatePage/PostInfo.tsx
  src/pages/PostCreatePage/index.ts
  src/pages/PostEditPage/PostEditPage.tsx
  src/pages/ProfileEditPage/components/ProfileEditInput.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/utils/validations.ts
Labels: 리팩터링

#247 에러 처리 관련 작업
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Modal/LoginForm.tsx
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/ErrorPage/Warning.tsx
  src/pages/ErrorPage/index.ts
  src/pages/NotFoundPage/index.ts
  src/pages/PostEditPage/PostEditPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/index.ts
  src/routes/router.tsx
  src/services/messageService.ts
  src/utils/apiError.ts
  src/utils/index.ts
Labels: 기능

#250 글씨 색깔 적용
  src/pages/FollowPage/FollowPage.tsx
  src/pages/FollowPage/UserList.tsx
Labels: 스타일

#256 팔로우 페이지 없음 디자인 추가
  src/assets/images/exclamation.png
  src/components/common/Exclamation/Exclamation.tsx
  src/components/common/Exclamation/index.ts
  src/components/common/index.ts
  src/components/domain/PostItem/PostItem.tsx
  src/components/domain/PostList/PostList.tsx
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ConversationPage/ConversationPage.tsx
  src/pages/FollowPage/UserList.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/NotificationsPage/components/NotificationItem.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/services/postService.ts
Labels: 스타일

#254 수정 페이지 디자인 수정
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/PostEditPage/PostEditPage.tsx
Labels: 스타일

#258 검색 페이지 관련 작업
  src/components/domain/Header/Header.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/components/CombinedSearchResults.tsx
  src/pages/SearchPage/components/PostSearchResult.tsx
  src/pages/SearchPage/components/SearchTypeButtons.tsx
  src/pages/SearchPage/components/UserList.tsx
  src/pages/SearchPage/components/UserSearchResult.tsx
  src/pages/SearchPage/components/index.ts
Labels: 리팩터링

#259 전체 페이지 스타일 피그마와 통일시키기
  src/assets/icons/index.ts
  src/assets/icons/logo.svg
  src/assets/images/index.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Exclamation/Exclamation.tsx
  src/components/domain/CommentItem/CommentItem.tsx
  src/components/domain/PostCard/constants.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ConversationPage/ConversationPage.tsx
  src/pages/FollowPage/FollowPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/ChannelInfo.tsx
  src/pages/NotificationsPage/NotificationsPage.tsx
  src/pages/NotificationsPage/components/NotificationItem.tsx
  src/pages/NotificationsPage/components/NotificationList.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/components/PostContent.tsx
  src/pages/PostPage/components/PostInfo.tsx
  src/pages/SearchPage/SearchPage.tsx
Labels: 기능, 리팩터링, 스타일

#257 간단한 리팩터링 작업
  src/components/domain/CommentItem/CommentItem.tsx
  src/hooks/index.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/LikeListPage/LikeListPage.tsx
  src/pages/PostPage/components/PostComment.tsx
  src/pages/PostPage/components/PostContent.tsx
  src/pages/PostPage/components/PostInfo.tsx
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/components/ProfileFullName.tsx
  src/pages/ProfileEditPage/components/ProfilePassword.tsx
  src/pages/ProfileEditPage/components/ProfileSetting.tsx
  src/pages/ProfileEditPage/components/ProfileSignOut.tsx
  src/pages/ProfilePage/ProfileHeader.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/components/CombinedSearchResults.tsx
  src/pages/SearchPage/constants.ts
  src/pages/SearchPage/types.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/SignUpPage/hooks/index.ts
  src/pages/SignUpPage/hooks/usePassword.ts
  src/services/channelService.ts
  src/services/commentService.ts
  src/services/postService.ts
  src/services/userService.ts
Labels: 리팩터링

#268 서버 초기화 후에 todo 주석 처리하기
  src/components/common/Cards/Card.stories.tsx
  src/components/common/Cards/Card.tsx
  src/components/common/Cards/index.ts
  src/components/common/HorizontalScroll/HorizontalScroll.stories.tsx
  src/components/common/index.ts
  src/components/domain/List/List.stories.tsx
  src/components/domain/List/List.tsx
  src/components/domain/List/index.ts
  src/components/domain/index.ts
  src/pages/SearchPage/components/PostList.tsx
  src/services/postService.ts
  src/services/userService.ts
  src/types/model.ts
Labels: 리팩터링

#273 글 작성 페이지 최적화 작업
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/PostCreatePage/components/ChannelList.tsx
  src/pages/PostEditPage/PostEditPage.tsx
  src/utils/validations.ts
Labels: 리팩터링

#269 임시 배포 작업
  src/api/snsApiClient.ts
  src/components/domain/CommentItem/CommentItem.stories.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/PostPage/components/PostComment.tsx
  src/routes/router.tsx
  vercel.json
Labels: 긴급

#277 스켈레톤 UI 적용
  index.html
  src/components/domain/PostCard/PostCardSkeleton.tsx
  src/components/domain/PostCard/index.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/ChannelPage/ChannelSkeleton.tsx
  src/pages/ChannelPage/index.ts
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ChatPage/ChatSkeleton.tsx
  src/pages/ChatPage/index.ts
  src/pages/ConversationPage/ConversationPage.tsx
  src/pages/ConversationPage/ConversationSkeleton.tsx
  src/pages/ConversationPage/index.ts
  src/pages/FollowPage/FollowPage.tsx
  src/pages/FollowPage/FollowSkeleton.tsx
  src/pages/FollowPage/components/UserList.tsx
  src/pages/FollowPage/components/index.ts
  src/pages/FollowPage/index.ts
  src/pages/HomePage/HomeSkeleton.tsx
  src/pages/HomePage/components/ChannelInfo.tsx
  src/pages/HomePage/index.ts
  src/pages/LikeListPage/LikeListSkeleton.tsx
  src/pages/LikeListPage/index.ts
  src/pages/PostPage/PostSkeleton.tsx
  src/pages/PostPage/index.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/ProfileSkeleton.tsx
  src/pages/ProfilePage/components/ProfileHeader.tsx
  src/pages/ProfilePage/components/ProfileHeaderSkeleton.tsx
  src/pages/ProfilePage/components/index.ts
  src/pages/ProfilePage/index.ts
  src/pages/index.ts
  src/routes/router.tsx
  src/services/messageService.ts
  src/services/postService.ts
Labels: 기능, 스타일

#271 유효하지 않은 토큰일 경우 로그인 제한(수정됨!!!)
  src/components/domain/Header/Header.tsx
  src/components/domain/Header/Notification.tsx
  src/hooks/useUser.ts
  src/pages/ErrorPage/ErrorPage.tsx
Labels: 리팩터링

#272 게시글 페이지를 최적화
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/components/PostComment.tsx
  src/pages/PostPage/components/PostContent.tsx
  src/pages/PostPage/components/PostInfo.tsx
  src/pages/PostPage/components/PostLike.tsx
  src/pages/channelPage/constants.ts
Labels: 리팩터링

#280 비밀번호 변경 후 홈페이지로 이동 처리
  src/pages/ProfileEditPage/components/ProfilePassword.tsx
Labels: 기능, 리팩터링

#282 전체 스타일 수정
  src/components/common/Badge/Badge.tsx
  src/components/common/Modal/Modal.tsx
  src/components/domain/Footer/Footer.tsx
  src/components/domain/Header/Header.tsx
  src/pages/ChannelPage/ChannelPage.tsx
  src/pages/ChatPage/ChatPage.tsx
  src/pages/ConversationPage/ConversationPage.tsx
  src/pages/FollowPage/FollowPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/ChannelInfo.tsx
  src/pages/LikeListPage/LikeListPage.tsx
  src/pages/NotificationsPage/NotificationsPage.tsx
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/PostEditPage/PostEditPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/components/PostContent.tsx
  src/pages/PostPage/components/PostInfo.tsx
  src/pages/PostPage/components/PostLike.tsx
  src/pages/ProfileEditPage/ProfileEditPage.tsx
  src/pages/ProfileEditPage/components/ProfileEditLabel.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/routes/Layout.tsx
  src/routes/LayoutWithFooter.tsx
Labels: 스타일

#285 followpage 애니메이션 적용되도록 수정
  src/pages/FollowPage/FollowSkeleton.tsx
  src/pages/FollowPage/components/UserList.tsx
  src/pages/FollowPage/index.ts
  src/routes/router.tsx
  src/services/userService.ts
Labels: 긴급

#288 글 작성, 수정 시 등록 문제 해결
  src/pages/PostCreatePage/PostCreatePage.tsx
  src/pages/PostEditPage/PostEditPage.tsx
Labels: 리팩터링, 버그
